# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  install:
    - pip install .

  build:
    - rm -rf ./dist || echo ""
    - py setup.py sdist
